import {Footer, PageHero} from '@/components/site-chrome';
import {User, Target, Eye, HeartHandshake, ShieldCheck, Sprout, PawPrint, Beef, Layers, Check, Quote, Wheat, Cpu, ChevronDown} from 'lucide-react';
export const metadata={title:'Our Story',description:'The Cattle Valley vision for a science-led goat and buffalo livestock ecosystem.'};
export default function About(){return <><PageHero eyebrow="Our story" title="Progress begins with a healthier habitat." copy="Cattle Valley is promoted by Cattle-Valley Limited (incorporated 11 February 2021) to enable eco-friendly, sustainable breeding and trading of goat and buffalo under the stall-feeding method."/><main className="content" style={{paddingTop:0}}>

<section className="shell about-intro"><span className="eyebrow">Our purpose</span><h2 className="display split-heading">A total ecosystem, built for the long term.</h2><p className="lede">On the lap of the Western Ghats, we are building a habitat with year-round green cover and wholesome water to enhance the breeding and growth of some of the most productive livestock breeds available today: Sirohi, Osmanabadi, Malabari and Beetal goats, alongside Murrah buffaloes.</p><div className="principles">{[[<Target size={18}/>,'Mission','Make scientific, ethical livestock farming more accessible and dependable.'],[<Eye size={18}/>,'Vision','Set a new standard for sustainable goat and buffalo ecosystems in India.'],[<HeartHandshake size={18}/>,'Care',"Individual tagging, quarantine sheds and an on-site veterinary hospital keep every animal's welfare non-negotiable."],[<ShieldCheck size={18}/>,'Integrity','PCA Act–compliant sourcing, biosecurity protocols and transparent systems guide every stage.']].map(([icon,t,p])=><div className="principle" key={t as string}><div className="principle-head">{icon}<b>{t}</b></div><p>{p}</p></div>)}</div></section>

<section className="shell"><div className="stat-grid"><div className="stat-hero"><img className="stat-hero-img" src="https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80" alt=""/><div className="stat-hero-overlay" aria-hidden="true"></div><div className="stat-hero-panel"><Sprout size={22} className="stat-hero-icon"/><div className="stat-hero-text"><strong>200 acres</strong><span>Lush green land at Usilampatti, A. Krishnapuram, Madurai, Tamil Nadu</span></div></div></div><div className="stat-card"><PawPrint size={20}/><strong>1,200+</strong><span>Goats farmed per year: Sirohi, Osmanabadi, Malabari & Beetal</span></div><div className="stat-card"><Beef size={20}/><strong>600+</strong><span>Murrah buffaloes farmed per year</span></div><div className="stat-card"><Layers size={20}/><strong>20</strong><span>Project components, from hydroponic fodder to a biogas plant</span></div></div></section>

<section className="section"><div className="shell"><span className="eyebrow">Twenty graceful components</span><h2 className="display section-title">One ecosystem, built end to end.</h2><p className="lede">From land to livestock to logistics, every layer of the project is engineered to work together.</p><div className="components-groups">{[
[<Sprout size={17}/>,'Land, infrastructure & development',['Eco-friendly land utilisation','Sustainable development model','Separate space for separate species','State-of-the-art rendering unit','Sophisticated ETP']],
[<Wheat size={17}/>,'Feeding & nutrition',['Hydroponic fodder cultivation','TMR machines for mixed ration','Silage for fodder storing','Mechanised feeding solutions','Rainwater harvesting for water saving']],
[<ShieldCheck size={17}/>,'Health, safety & compliance',['Own site veterinary hospital','Biosecurity systems for quality control','Quarantine sheds for health monitoring','Individual tagging for animal identification','Total insurance against eventualities']],
[<Cpu size={17}/>,'Energy, technology & growth',['Solar system for energy','Biogas plant for recycling','Multi-dimensional marketing options','Diverse product potentials','Smart and digital system for online monitoring']],
].map(([icon,title,items],i)=><details className="components-group" key={title as string} open={i===0}><summary><span className="components-group-head">{icon}{title}</span><span className="components-group-count">{(items as string[]).length} items</span><ChevronDown size={16} className="components-group-chevron"/></summary><ul>{(items as string[]).map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul></details>)}</div></div></section>

<section className="section timeline-section"><div className="shell"><span className="eyebrow">A measured evolution</span><h2 className="display section-title">Rooted in practice. Ready for tomorrow.</h2><div className="steps">{[['01','Incorporated','Cattle-Valley Limited was incorporated on 11 February 2021 to build a science-led livestock ecosystem.'],['02','200 acres secured','A lush green site at Usilampatti, A. Krishnapuram, Madurai, Tamil Nadu, set aside for rearing, trading, fodder and civil works.'],['03','Ecosystem building','Hydroponic fodder, TMR mixing, silage storage, solar power, biogas recycling and an on-site veterinary hospital.'],['04','Structured farming','Goats and buffaloes reared each year under the stall-feeding method, with individual tagging and biosecurity protocols.'],['05','Responsible trading','PCA Act–compliant sourcing and transport, with quarantine and antemortem checks before every animal reaches the farm.'],['06','Farm tourism ahead','Plans for a biodiversity park, poultry farm and farm-tourism experience as the ecosystem expands.']].map(([n,t,p])=><div className="step" key={n}><div className="step-no">{n}</div><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>

<section className="section"><div className="shell"><span className="eyebrow">Leadership</span><h2 className="display section-title">The people steering Cattle Valley.</h2>

<div className="card leader leader-featured"><div className="leader-portrait"><img src="/images/team/zainulabdeen.webp" alt="Zainulabdeen Abdullatheef"/></div><div className="leader-body"><b>Zainulabdeen Abdullatheef</b><em>Chairman</em><p>A well-qualified sales and marketing professional recognised by internationally acclaimed companies: Topper & Winner of the Middle East Championship programme (2016–17) run by RIDGE Tools, Elyria, Ohio, USA. He spent 15 years as a Corporate Sales Manager, presenting at seminars across Germany, Belgium and the USA, and is a speaker, trainer, team leader, and dedicated humanitarian and social worker.</p></div></div>

<span className="tier-label">Office bearers</span><div className="leaders-standard">{[['Abdulla Palappatta Kulangara Thodika','Vice-Chairman','/images/team/abdulla-thodika.webp','An oil and gas engineering design and construction professional with 17 years of experience, currently a corporate engineering manager in the oil and gas division of a major LSTK contracting company in KSA. He is also the Managing Partner of a food retail company and leads a firm in bulk trading of home appliances across the GCC.'],['Mujeebali Erechan Thodika Poonkuzhi','Vice-Chairman','/images/team/mujeeb-ali.webp','A seasoned HR & Administration professional with over 30 years of experience in Saudi Arabia, including as President’s Office Manager at a well-known company in Riyadh. Beyond his corporate career, he is an active humanitarian and social worker contributing his time and expertise to several organisations.'],['Asif Iqbal Puthankulam Mohammed','Managing Director','/images/team/asif-iqbal.webp','Managing Director of OPTOMAC Technical Services, bringing over two decades of experience to the global energy sector. Holding a B.E. in Electronics & Telecommunications, he has spent 15 years steering OPTOMAC as a trusted partner in the Oil & Gas industry, delivering specialised technical solutions and optimised asset integrity.']].map(([n,t,photo,p])=><div className="card leader" key={n}><div className="leader-portrait">{photo?<img src={photo} alt={n}/>:<User size={34}/>}</div><div className="leader-body"><b>{n}</b><em>{t}</em><p>{p}</p></div></div>)}</div>

<span className="tier-label">Project consultants</span><div className="leaders-vice">{[['Dr. Pilanku Veettil Mohanan','Doctor','/images/team/mohanan-pilankuveetil.webp','An internationally acclaimed figure in livestock management and slaughterhouse establishment, having consulted on projects across India. He has published 2,000+ articles and 30+ books, delivered 150+ talks, and holds credentials including HACCP & ISO Lead auditor, and roles with FIB (GoK), KEL, CEE India, Meat Products of India and INDOCERT.'],['Ar. Bijoy','Architect','','Founder and Principal Architect at Tropics Architects, Calicut (est. 2010). Educated in Bangalore, he has worked on prestigious projects including the Microsoft campus in Hyderabad and the Cisco campus in Bangalore. Tropics Architects favours a minimalistic approach that lets developments add to, rather than compete with, their natural surroundings.']].map(([n,t,photo,p])=><div className="card leader" key={n}><div className="leader-portrait">{photo?<img src={photo} alt={n}/>:<User size={40}/>}</div><div className="leader-body"><b>{n}</b><em>{t}</em><p>{p}</p></div></div>)}</div>

</div></section>

<section className="section board-section"><div className="shell"><span className="eyebrow">Board & governance</span><h2 className="display section-title">Backed by an experienced team.</h2><div className="board-groups">{([['Ex-office bearers',[['Kallattayil Mohamed Asharaf','Promoter Director',''],['Ali Varikunnath','Promoter Director','ali-varikunnath']]],['Key managerial personnel',[['Venthanathayil Shajahan','Chief Financial Officer','shajahan-v'],['Praison Koshy','Company Secretary','praison-koshy']]],['Mentor',[['Kallianam Veettil Assan Koya','Mentor','kallianam-assan-koya']]],['On-site manager',[['Karthick Kumar','Doctor','karthick-kumar']]],['Elite board members',[['Kakkat Ali Ibrahim','Director','kakkat-ali-ibrahim'],['Mohamed Safwan','Director','mohamed-safwan'],['Mujeebu Rahiman Alikutty Valiyavalappil','Director','mujeebu-rahiman'],['Karuppamveettil Sabeer','Director','karuppamveettil-sabeer'],['Shaji','Director','shaji'],['Shameel','Director','shameel-pp'],['Shahith Mathilakathveettil Sharafudheen','Director','shahith-sharafudheen'],['Mohamed Shahzad Abdul Salam','Director','mohamed-shahzad'],['Fazil Rahim','Director','fazil-rahim'],['Habeebu Rahiman Meleveettil','Director','habeebu-rahiman'],['Abbas Chemban','Director','abbas-chemban'],['Ajmal Naseeb','Director','ajmal-naseeb'],['Valiyakath Asharaf Muhamed Fayiz','Director','valiyakath-asharaf-fayiz'],['Aboobakker Sidhiq Mohammed Shafeeq','Director',''],['Puthiyaveetil Abdul Latheef Haroon Rasheed','Director','haroon-rasheed'],['Anwar Hassan','Director','anwar-hassan']]]] as [string,[string,string,string][]][]).map(([group,people])=><div className="board-group" key={group}><h4>{group}</h4><div className="board-people">{people.map(([n,r,slug])=><div className="board-person" key={n}><div className="board-avatar">{slug?<img src={`/images/team/${slug}.webp`} alt={n}/>:<User size={18}/>}</div><div className="board-person-body"><b>{n}</b><span>{r}</span></div></div>)}</div></div>)}</div></div></section>

<section className="section"><div className="shell"><div className="quote"><Quote color="#e0b84f" size={30}/><p>"Cash combined with courage in a time of crisis is priceless."</p><small>WARREN BUFFETT</small></div><p className="lede final-salute">True, the whole world is facing a crisis. Hold on to your health, your healthy habits, and your habitual chores. And above all, hold on to His Grace. Cattle Valley opens the door to holding on to healthy habits and His Grace. The choice is yours. Once you join hands with us, we will, together, move up. Warm welcome.</p></div></section>

</main><Footer/></>}
