'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { BarChart3, FileText, FolderOpen, ImageIcon, LayoutDashboard, MapPin, MessageSquareQuote, Plus, Save, Settings, Trash2, X } from 'lucide-react';
import { defaultHubs, localCmsStorageKey, normaliseHub } from '@/lib/local-cms';

type Status = 'Published' | 'Draft' | 'Active' | 'Upcoming';
type Item = { id: string; title: string; detail: string; status: Status; location?: string; description?: string; auctionDate?: string; whatsapp?: string; image?: string; category?: string; tags?: string[]; slug?: string; createdAt?: string; subheading?: string; readTime?: string; content?: string; quote?: string; url?: string; size?: number };
type Module = 'Overview' | 'Blogs' | 'Hubs & auctions' | 'Gallery' | 'Testimonials' | 'Documents' | 'Site settings';
type ContentModule = Exclude<Module, 'Overview' | 'Site settings'>;
type CmsState = Record<ContentModule, Item[]> & { settings: { siteName: string; email: string; phone: string; address: string; heroImage?: string; youtubeUrl?: string; instagramUrl?: string } };
const photo = 'https://images.unsplash.com/photo-1523742810063-7de5c3c16809?auto=format&fit=crop&w=900&q=80';
const initialState: CmsState = { Blogs: [{ id: 'post-1', title: 'The future of sustainable livestock is local', detail: 'Sustainable Farming · 6 min read', subheading: 'A more considered model for India’s livestock future.', content: 'At Graze Valley, sustainability is a daily practice built through better animal care, transparent systems, and practical local knowledge.', category: 'Sustainable Farming', readTime: '6 min read', image: photo, status: 'Published' }], 'Hubs & auctions': defaultHubs.map(hub => ({ ...hub, detail: `${hub.location} · Auction: ${hub.auctionDate}` })), Gallery: [{ id: 'gallery-1', title: 'Healthy herd at sunrise', detail: 'Latest', category: 'Latest', slug: 'latest', image: photo, createdAt: new Date().toISOString(), status: 'Published' }], Testimonials: [{ id: 'testimonial-1', title: 'Dr. Nisha Rahman', detail: 'Veterinary Consultant', quote: 'The approach is refreshingly structured. You can see the care in the animals and the systems behind them.', status: 'Published' }], Documents: [{ id: 'document-1', title: 'Animal wellness standards', detail: 'PDF · Policies', category: 'Policies', url: '#', createdAt: new Date().toISOString(), status: 'Published' }], settings: { siteName: 'Graze Valley', email: 'info@grazevalley.com', phone: '+91 98765 43210', address: 'Malappuram, Kerala, India', heroImage: 'https://images.unsplash.com/photo-1535435706-3f1b16e64a8a?auto=format&fit=crop&w=2200&q=90', youtubeUrl: '', instagramUrl: '' } };
const nav: { label: Module; icon: typeof LayoutDashboard }[] = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Blogs', icon: FileText }, { label: 'Hubs & auctions', icon: MapPin }, { label: 'Gallery', icon: ImageIcon }, { label: 'Testimonials', icon: MessageSquareQuote }, { label: 'Documents', icon: FolderOpen }, { label: 'Site settings', icon: Settings }];
function readCms(): CmsState { try { const raw = window.localStorage.getItem(localCmsStorageKey); if (!raw) return initialState; const saved = JSON.parse(raw); const state = { ...initialState, ...saved }; state['Hubs & auctions'] = (state['Hubs & auctions'] || []).map(normaliseHub).map((hub: Item) => ({ ...hub, detail: `${hub.location} · Auction: ${hub.auctionDate}` })); return state; } catch { return initialState; } }
function fileUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }

export function AdminCms() {
  const [active, setActive] = useState<Module>('Overview'); const [cms, setCms] = useState<CmsState>(initialState); const [ready, setReady] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [notice, setNotice] = useState('');
  useEffect(() => { setCms(readCms()); setReady(true); }, []); useEffect(() => { if (ready) window.localStorage.setItem(localCmsStorageKey, JSON.stringify(cms)); }, [cms, ready]);
  const items = active !== 'Overview' && active !== 'Site settings' ? cms[active] : []; const metrics = useMemo(() => ({ blogs: cms.Blogs.length, hubs: cms['Hubs & auctions'].length, gallery: cms.Gallery.length, documents: cms.Documents.length }), [cms]);
  function startNew() { const base: Item = { id: crypto.randomUUID(), title: '', detail: '', status: active === 'Hubs & auctions' ? 'Upcoming' : 'Draft', createdAt: new Date().toISOString() }; if (active === 'Hubs & auctions') Object.assign(base, { location: '', description: '', auctionDate: '', whatsapp: '', image: defaultHubs[0].image }); setEditing(base); }
  function save(item: Item) { if (active === 'Overview' || active === 'Site settings') return; setCms(previous => ({ ...previous, [active]: previous[active].some(record => record.id === item.id) ? previous[active].map(record => record.id === item.id ? item : record) : [item, ...previous[active]] })); setEditing(null); setNotice('Saved locally. Refresh the relevant public page to see the update.'); }
  function remove(id: string) { if (active === 'Overview' || active === 'Site settings') return; setCms(previous => ({ ...previous, [active]: previous[active].filter(item => item.id !== id) })); setNotice('Item removed.'); }
  function saveSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setCms(value => ({ ...value, settings: { siteName: String(data.get('siteName')), email: String(data.get('email')), phone: String(data.get('phone')), address: String(data.get('address')), heroImage: String(data.get('heroImage')), youtubeUrl: String(data.get('youtubeUrl')), instagramUrl: String(data.get('instagramUrl')) } })); setNotice('Site settings saved locally.'); }
  return <main className="admin"><div className="shell admin-grid"><aside className="card admin-nav"><div className="admin-brand"><span className="eyebrow">Graze Valley</span><b className="display">Content<br/>Studio</b></div><nav aria-label="Admin navigation">{nav.map(({ label, icon: Icon }) => <button className={`admin-nav-item ${active === label ? 'is-active' : ''}`} onClick={() => { setActive(label); setEditing(null); setNotice(''); }} key={label}><Icon size={16}/>{label}</button>)}</nav><button className="admin-reset" onClick={() => { window.localStorage.removeItem(localCmsStorageKey); setCms(initialState); setNotice('Demo content restored.'); }}>Restore demo data</button></aside><section className="admin-content"><div className="admin-top"><div><span className="eyebrow">Local CMS mode</span><h1 className="display">{active}</h1></div>{active !== 'Overview' && active !== 'Site settings' && <button className="button dark" onClick={startNew}><Plus size={16}/>Add {active === 'Hubs & auctions' ? 'hub' : active.slice(0, -1)}</button>}</div>{notice && <div className="admin-notice">{notice}<button onClick={() => setNotice('')} aria-label="Close"><X size={14}/></button></div>}{active === 'Overview' && <Overview metrics={metrics}/>} {active === 'Site settings' && <SettingsForm settings={cms.settings} onSubmit={saveSettings}/>} {active !== 'Overview' && active !== 'Site settings' && <><p className="admin-helper">Changes are saved in this browser. Supabase will make this shared and secure when you are ready to publish.</p><div className="admin-table card">{items.map(item => <div className="admin-row" key={item.id}><div><b>{item.title}</b><span>{item.detail}</span></div><div className="row-actions">{active !== 'Testimonials'&&<span className={`status ${item.status.toLowerCase()}`}>{item.status}</span>}<button onClick={() => setEditing(item)}>Edit</button><button className="danger" onClick={() => remove(item.id)} aria-label={`Delete ${item.title}`}><Trash2 size={15}/></button></div></div>)}{items.length === 0 && <div className="admin-empty">No entries yet. Add your first one above.</div>}</div>{editing && <ContentEditor active={active} item={editing} onCancel={() => setEditing(null)} onSave={save}/>}</>}</section></div></main>;
}
function Overview({ metrics }: { metrics: { blogs: number; hubs: number; gallery: number; documents: number } }) { return <><p className="admin-helper">Manage your local content from one place. Hubs and auctions, gallery images, documents, and testimonials are ready for editing.</p><div className="dashboard-cards">{[[String(metrics.blogs), 'Blog posts', FileText], [String(metrics.hubs), 'Hub locations', MapPin], [String(metrics.gallery), 'Gallery images', ImageIcon], [String(metrics.documents), 'Documents', FolderOpen]].map(([number, title, Icon]) => { const Glyph = Icon as typeof BarChart3; return <div className="card admin-metric" key={title as string}><Glyph size={18}/><b>{number as string}</b><span>{title as string}</span></div>; })}</div><div className="card admin-welcome"><BarChart3 size={24}/><div><h2 className="display">Your content, organised.</h2><p>Use the gallery category and document tools to keep each public collection current.</p></div></div></> }
function ContentEditor({ active, item, onCancel, onSave }: { active: ContentModule; item: Item; onCancel: () => void; onSave: (item: Item) => void }) { if (active === 'Hubs & auctions') return <HubEditor item={item} onCancel={onCancel} onSave={onSave}/>; if (active === 'Gallery') return <GalleryEditor item={item} onCancel={onCancel} onSave={onSave}/>; if (active === 'Blogs') return <BlogEditor item={item} onCancel={onCancel} onSave={onSave}/>; if (active === 'Testimonials') return <TestimonialEditor item={item} onCancel={onCancel} onSave={onSave}/>; return <DocumentEditor item={item} onCancel={onCancel} onSave={onSave}/>; }
function Frame({ children, title, onCancel }: { children: React.ReactNode; title: string; onCancel: () => void }) { return <div className="card editor"><div className="editor-heading"><h2 className="display">{title}</h2><button type="button" onClick={onCancel} aria-label="Close editor"><X size={18}/></button></div>{children}</div> }
function HubEditor({ item, onCancel, onSave }: { item: Item; onCancel: () => void; onSave: (item: Item) => void }) { const [image, setImage] = useState(item.image || ''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const selected=String(d.get('auctionDate')); const formatted=selected?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${selected}T00:00:00`)):''; const file = d.get('image') as File; const uploaded = file?.size ? await fileUrl(file) : image; onSave({ ...item, title: String(d.get('title')), location: String(d.get('location')), description: String(d.get('description')), auctionDate: formatted, whatsapp: String(d.get('whatsapp')), image: uploaded, status: d.get('status') as Status, detail: `${d.get('location')} · Auction: ${formatted}` }); } const iso=item.auctionDate?new Date(item.auctionDate).toISOString().slice(0,10):''; return <Frame title={item.title ? 'Edit hub & auction' : 'New hub'} onCancel={onCancel}><form onSubmit={submit}><Field label="Hub name" name="title" value={item.title}/><Field label="Location" name="location" value={item.location} placeholder="Malappuram, Kerala"/><Field label="Hub description" name="description" value={item.description} textarea/><div className="field"><label htmlFor="auctionDate">Upcoming auction date</label><input id="auctionDate" name="auctionDate" type="date" defaultValue={iso} required/></div><Field label="Auction WhatsApp number" name="whatsapp" value={item.whatsapp} placeholder="919876543210" hint="Country code only—no +, spaces, or punctuation. Each hub can have a different number."/><Upload label="Hub photo" name="image" image={image} onImage={setImage} required={!image}/><StatusField value={item.status}/><Actions onCancel={onCancel}/></form></Frame> }
function BlogEditor({ item, onCancel, onSave }: { item: Item; onCancel: () => void; onSave: (item: Item) => void }) { const [image, setImage] = useState(item.image || ''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const file = d.get('image') as File; const uploaded = file?.size ? await fileUrl(file) : image; onSave({ ...item, title: String(d.get('title')), subheading: String(d.get('subheading')), content: String(d.get('content')), category: String(d.get('category')), readTime: String(d.get('readTime')), image: uploaded, status: d.get('status') as Status, detail: `${d.get('category')} · ${d.get('readTime')}` }); } return <Frame title={item.title ? 'Edit blog' : 'New blog'} onCancel={onCancel}><form onSubmit={submit}><Field label="Headline" name="title" value={item.title}/><Field label="Subheading" name="subheading" value={item.subheading} textarea/><Field label="Article content" name="content" value={item.content} textarea/><Field label="Category" name="category" value={item.category} placeholder="Sustainable Farming"/><Field label="Read time" name="readTime" value={item.readTime} placeholder="6 min read"/><Upload label="Cover image" name="image" image={image} onImage={setImage}/><StatusField value={item.status}/><Actions onCancel={onCancel}/></form></Frame> }
function GalleryEditor({ item, onCancel, onSave }: { item: Item; onCancel: () => void; onSave: (item: Item) => void }) { const [image, setImage] = useState(item.image || ''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const tags=String(d.get('category')).split(',').map(tag=>tag.trim()).filter(Boolean).map(slugify); const category = tags[0] || 'general'; const file = d.get('image') as File; const uploaded = file?.size ? await fileUrl(file) : image; onSave({ ...item, title: String(d.get('title')), category, tags, slug: category, image: uploaded, createdAt: item.createdAt || new Date().toISOString(), status: d.get('status') as Status, detail: tags.join(', ') || 'General' }); } return <Frame title={item.title ? 'Edit gallery image' : 'Add gallery image'} onCancel={onCancel}><form onSubmit={submit}><Field label="Image title" name="title" value={item.title}/><Field label="Category tags" name="category" value={item.tags?.join(', ') || item.category} placeholder="Facilities, Livestock, Events" hint="Type one or more tags separated by commas. New tags create gallery categories automatically."/><Upload label="Gallery image" name="image" image={image} onImage={setImage} required={!image}/><StatusField value={item.status}/><Actions onCancel={onCancel}/></form></Frame> }
function TestimonialEditor({ item, onCancel, onSave }: { item: Item; onCancel: () => void; onSave: (item: Item) => void }) { function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); onSave({ ...item, title: String(d.get('title')), detail: String(d.get('detail')), quote: String(d.get('quote')), status: 'Published' }); } return <Frame title={item.title ? 'Edit testimonial' : 'Add testimonial'} onCancel={onCancel}><form onSubmit={submit}><Field label="Person’s name" name="title" value={item.title}/><Field label="Role / details" name="detail" value={item.detail} placeholder="Veterinary Consultant"/><Field label="Testimonial" name="quote" value={item.quote} textarea/><Actions onCancel={onCancel}/></form></Frame> }
function DocumentEditor({ item, onCancel, onSave }: { item: Item; onCancel: () => void; onSave: (item: Item) => void }) { const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const file = d.get('document') as File; if (!item.url && !file?.size) return setError('Please choose a document.'); if (file?.size > 5 * 1024 * 1024) return setError('Documents must be 5 MB or smaller.'); const url = file?.size ? await fileUrl(file) : item.url; onSave({ ...item, title: String(d.get('title')), category: String(d.get('category')) || 'General', detail: file?.size ? `${file.name} · ${(file.size / 1024 / 1024).toFixed(1)} MB` : item.detail, url, size: file?.size || item.size, createdAt: item.createdAt || new Date().toISOString(), status: d.get('status') as Status }); } return <Frame title={item.title ? 'Edit document' : 'Upload document'} onCancel={onCancel}><form onSubmit={submit}><Field label="Document title" name="title" value={item.title}/><Field label="Category" name="category" value={item.category} placeholder="Policies"/><div className="field"><label htmlFor="document">Document file</label><input id="document" name="document" type="file" accept=".pdf,.doc,.docx"/><small>PDF, DOC, or DOCX · maximum file size 5 MB.</small></div>{error && <p className="form-error">{error}</p>}<StatusField value={item.status}/><Actions onCancel={onCancel}/></form></Frame> }
function Field({ label, name, value, placeholder, textarea, hint }: { label: string; name: string; value?: string; placeholder?: string; textarea?: boolean; hint?: string }) { return <div className="field"><label htmlFor={name}>{label}</label>{textarea ? <textarea id={name} name={name} defaultValue={value} rows={3} required/> : <input id={name} name={name} defaultValue={value} placeholder={placeholder} required/>}{hint && <small>{hint}</small>}</div> }
function Upload({ label, name, image, onImage, required }: { label: string; name: string; image: string; onImage: (value: string) => void; required?: boolean }) { async function change(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (file) onImage(await fileUrl(file)); } return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type="file" accept="image/*" required={required} onChange={change}/>{image && <img className="editor-preview" src={image} alt="Upload preview"/>}</div> }
function StatusField({ value }: { value: Status }) { return <div className="field"><label htmlFor="status">Status</label><select id="status" name="status" defaultValue={value}><option>Draft</option><option>Published</option><option>Active</option><option>Upcoming</option></select></div> }
function Actions({ onCancel }: { onCancel: () => void }) { return <div className="editor-actions"><button type="button" className="button light" onClick={onCancel}>Cancel</button><button className="button dark"><Save size={16}/>Save changes</button></div> }
function SettingsForm({ settings, onSubmit }: { settings: CmsState['settings']; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="card editor settings-form" onSubmit={onSubmit}><Field label="Site name" name="siteName" value={settings.siteName}/><Field label="Email" name="email" value={settings.email}/><Field label="Phone" name="phone" value={settings.phone}/><Field label="Address" name="address" value={settings.address} textarea/><Field label="Hero banner image URL" name="heroImage" value={settings.heroImage} placeholder="https://…" hint="Paste a hosted image URL for the homepage hero banner."/><Field label="YouTube channel or latest-video URL" name="youtubeUrl" value={settings.youtubeUrl} placeholder="https://youtube.com/@grazevalley"/><Field label="Instagram profile URL" name="instagramUrl" value={settings.instagramUrl} placeholder="https://instagram.com/grazevalley"/><button className="button dark"><Save size={16}/>Save settings</button></form> }
