'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { BarChart3, FileText, FolderOpen, ImageIcon, LayoutDashboard, LogOut, MapPin, Menu, MessageSquareQuote, Plus, Save, Settings as SettingsIcon, Trash2, X } from 'lucide-react';
import { Item, Settings, Status, deleteItem, fetchBlogPosts, fetchDocuments, fetchGalleryImages, fetchHubs, fetchSettings, fetchTestimonials, formatAuctionDate, saveItem, saveSettings as persistSettings, uploadFile } from '@/lib/cms';
import { supabase } from '@/lib/supabase/client';

type Module = 'Overview' | 'Blogs' | 'Hubs & auctions' | 'Gallery' | 'Testimonials' | 'Documents' | 'Site settings';
type ContentModule = Exclude<Module, 'Overview' | 'Site settings'>;
type CmsState = Record<ContentModule, Item[]> & { settings: Settings };
const emptySettings: Settings = { siteName: '', email: '', phone: '', address: '', heroImage: '', youtubeUrl: '', instagramUrl: '' };
const emptyState: CmsState = { Blogs: [], 'Hubs & auctions': [], Gallery: [], Testimonials: [], Documents: [], settings: emptySettings };
const nav: { label: Module; icon: typeof LayoutDashboard }[] = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Blogs', icon: FileText }, { label: 'Hubs & auctions', icon: MapPin }, { label: 'Gallery', icon: ImageIcon }, { label: 'Testimonials', icon: MessageSquareQuote }, { label: 'Documents', icon: FolderOpen }, { label: 'Site settings', icon: SettingsIcon }];

export function AdminCms() {
  const router = useRouter();
  const [active, setActive] = useState<Module>('Overview'); const [cms, setCms] = useState<CmsState>(emptyState); const [ready, setReady] = useState(false); const [loadError, setLoadError] = useState(''); const [editing, setEditing] = useState<Item | null>(null); const [notice, setNotice] = useState(''); const [userEmail, setUserEmail] = useState('');
  const [dirty, setDirty] = useState(false); const [pendingAction, setPendingAction] = useState<(() => void) | null>(null); const [pendingDelete, setPendingDelete] = useState<Item | null>(null); const [sidebarOpen, setSidebarOpen] = useState(false);
  useEffect(() => { let cancelled = false; (async () => { try { const [Blogs, Hubs, Gallery, Testimonials, Documents, settings] = await Promise.all([fetchBlogPosts(), fetchHubs(), fetchGalleryImages(), fetchTestimonials(), fetchDocuments(), fetchSettings()]); if (cancelled) return; setCms({ Blogs, 'Hubs & auctions': Hubs, Gallery, Testimonials, Documents, settings }); setReady(true); } catch (err) { if (cancelled) return; setLoadError(err instanceof Error ? err.message : 'Could not reach Supabase.'); setReady(true); } })(); return () => { cancelled = true; }; }, []);
  useEffect(() => { supabase.auth.getUser().then(({ data }) => setUserEmail(data.user?.email || '')); }, []);
  useEffect(() => { document.body.style.overflow = sidebarOpen ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [sidebarOpen]);
  useEffect(() => { function handler(e: BeforeUnloadEvent) { if (dirty) { e.preventDefault(); e.returnValue = ''; } } window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  async function signOut() { await supabase.auth.signOut(); router.push('/login'); router.refresh(); }
  function withUnsavedGuard(action: () => void) { if (dirty) setPendingAction(() => action); else action(); }
  function openEditor(item: Item) { setDirty(false); setEditing(item); }
  const items = active !== 'Overview' && active !== 'Site settings' ? cms[active] : []; const metrics = useMemo(() => ({ blogs: cms.Blogs.length, hubs: cms['Hubs & auctions'].length, gallery: cms.Gallery.length, documents: cms.Documents.length }), [cms]);
  function startNew() { const base: Item = { id: '', title: '', detail: '', status: active === 'Hubs & auctions' ? 'Upcoming' : 'Draft', createdAt: new Date().toISOString() }; if (active === 'Hubs & auctions') Object.assign(base, { location: '', description: '', auctionDate: '', whatsapp: '', image: '' }); openEditor(base); }
  async function save(item: Item) { if (active === 'Overview' || active === 'Site settings') return; try { const isNew = !item.id; const saved = await saveItem(active, item, isNew); setCms(previous => ({ ...previous, [active]: isNew ? [saved, ...previous[active]] : previous[active].map(record => record.id === item.id ? saved : record) })); setDirty(false); setEditing(null); setNotice('Saved to the live site.'); } catch (err) { setNotice(err instanceof Error ? err.message : 'Failed to save.'); } }
  async function remove(id: string) { if (active === 'Overview' || active === 'Site settings') return; try { await deleteItem(active, id); setCms(previous => ({ ...previous, [active]: previous[active].filter(item => item.id !== id) })); setNotice('Item removed.'); } catch (err) { setNotice(err instanceof Error ? err.message : 'Failed to delete.'); } }
  async function saveSettings(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const next: Settings = { siteName: String(data.get('siteName')), email: String(data.get('email')), phone: String(data.get('phone')), address: String(data.get('address')), heroImage: String(data.get('heroImage')), youtubeUrl: String(data.get('youtubeUrl')), instagramUrl: String(data.get('instagramUrl')) }; try { const saved = await persistSettings(next); setCms(value => ({ ...value, settings: saved })); setDirty(false); setNotice('Site settings saved.'); } catch (err) { setNotice(err instanceof Error ? err.message : 'Failed to save settings.'); } }
  function switchTab(label: Module) { withUnsavedGuard(() => { setActive(label); setEditing(null); setDirty(false); setNotice(''); setSidebarOpen(false); }); }
  const markDirty = () => setDirty(true);
  return <div className="admin"><div className="admin-shell">
    <aside className={`admin-sidebar ${sidebarOpen ? 'is-open' : ''}`}>
      <div className="admin-brand"><span className="eyebrow">Graze Valley</span><b className="display">Content<br/>Studio</b></div>
      <nav aria-label="Admin navigation">{nav.map(({ label, icon: Icon }) => <button className={`admin-nav-item ${active === label ? 'is-active' : ''}`} onClick={() => switchTab(label)} key={label}><Icon size={16}/>{label}</button>)}</nav>
      <div className="admin-sidebar-foot">{userEmail && <p className="admin-user">{userEmail}</p>}<button className="admin-reset" onClick={() => withUnsavedGuard(signOut)}><LogOut size={13} style={{ verticalAlign: 'middle', marginRight: 4 }}/>Sign out</button></div>
    </aside>
    {sidebarOpen && <button className="admin-overlay" aria-label="Close menu" onClick={() => setSidebarOpen(false)}/>}
    <div className="admin-main">
      <header className="admin-topbar"><button className="admin-hamburger" aria-label="Open menu" onClick={() => setSidebarOpen(true)}><Menu size={19}/></button><span className="admin-topbar-title">{active}</span></header>
      <section className="admin-content">
        <div className="admin-top"><div><span className="eyebrow">Connected to Supabase</span><h1 className="display">{active}</h1></div>{active !== 'Overview' && active !== 'Site settings' && <button className="button dark" onClick={() => withUnsavedGuard(startNew)}><Plus size={16}/>Add {active === 'Hubs & auctions' ? 'hub' : active.slice(0, -1)}</button>}</div>
        {notice && <div className="admin-notice">{notice}<button onClick={() => setNotice('')} aria-label="Close"><X size={14}/></button></div>}
        {loadError && <div className="admin-notice">Could not load content from Supabase: {loadError}</div>}
        {!ready && <p className="admin-helper">Loading…</p>}
        {ready && active === 'Overview' && <Overview metrics={metrics}/>}
        {ready && active === 'Site settings' && <SettingsForm settings={cms.settings} onSubmit={saveSettings} onDirty={markDirty}/>}
        {ready && active !== 'Overview' && active !== 'Site settings' && <><p className="admin-helper">Changes save straight to the database and go live on the public site immediately.</p><div className="admin-table card">{items.map(item => <div className="admin-row" key={item.id}><div><b>{item.title}</b><span>{item.detail}</span></div><div className="row-actions">{active !== 'Testimonials'&&<span className={`status ${item.status.toLowerCase()}`}>{item.status}</span>}<button onClick={() => withUnsavedGuard(() => openEditor(item))}>Edit</button><button className="danger" onClick={() => setPendingDelete(item)} aria-label={`Delete ${item.title}`}><Trash2 size={15}/></button></div></div>)}{items.length === 0 && <div className="admin-empty">No entries yet. Add your first one above.</div>}</div>{editing && <ContentEditor active={active} item={editing} onCancel={() => withUnsavedGuard(() => { setEditing(null); setDirty(false); })} onSave={save} onDirty={markDirty}/>}</>}
      </section>
    </div>
  </div>
  {pendingDelete && <ConfirmDialog title="Delete this item?" message={`Delete "${pendingDelete.title}"? This can't be undone.`} confirmLabel="Delete" tone="danger" onConfirm={() => { remove(pendingDelete.id); setPendingDelete(null); }} onCancel={() => setPendingDelete(null)}/>}
  {pendingAction && <ConfirmDialog title="Discard unsaved changes?" message="You have changes that haven't been saved. Leave without saving?" confirmLabel="Discard changes" tone="danger" onConfirm={() => { const action = pendingAction; setPendingAction(null); setDirty(false); action(); }} onCancel={() => setPendingAction(null)}/>}
  </div>;
}
function ConfirmDialog({ title, message, confirmLabel, tone, onConfirm, onCancel }: { title: string; message: string; confirmLabel: string; tone?: 'danger'; onConfirm: () => void; onCancel: () => void }) {
  return <div className="confirm-overlay" onClick={onCancel}><div className="confirm-dialog card" onClick={e => e.stopPropagation()} role="alertdialog" aria-modal="true" aria-label={title}><h3>{title}</h3><p>{message}</p><div className="confirm-actions"><button className="button light" onClick={onCancel}>Cancel</button><button className={`button dark ${tone === 'danger' ? 'confirm-danger' : ''}`} onClick={onConfirm}>{confirmLabel}</button></div></div></div>;
}
function Overview({ metrics }: { metrics: { blogs: number; hubs: number; gallery: number; documents: number } }) { return <><p className="admin-helper">Manage your live content from one place. Hubs and auctions, gallery images, documents, and testimonials are ready for editing.</p><div className="dashboard-cards">{[[String(metrics.blogs), 'Blog posts', FileText], [String(metrics.hubs), 'Hub locations', MapPin], [String(metrics.gallery), 'Gallery images', ImageIcon], [String(metrics.documents), 'Documents', FolderOpen]].map(([number, title, Icon]) => { const Glyph = Icon as typeof BarChart3; return <div className="card admin-metric" key={title as string}><Glyph size={18}/><b>{number as string}</b><span>{title as string}</span></div>; })}</div><div className="card admin-welcome"><BarChart3 size={24}/><div><h2 className="display">Your content, organised.</h2><p>Use the gallery category and document tools to keep each public collection current.</p></div></div></> }
function ContentEditor({ active, item, onCancel, onSave, onDirty }: { active: ContentModule; item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { if (active === 'Hubs & auctions') return <HubEditor item={item} onCancel={onCancel} onSave={onSave} onDirty={onDirty}/>; if (active === 'Gallery') return <GalleryEditor item={item} onCancel={onCancel} onSave={onSave} onDirty={onDirty}/>; if (active === 'Blogs') return <BlogEditor item={item} onCancel={onCancel} onSave={onSave} onDirty={onDirty}/>; if (active === 'Testimonials') return <TestimonialEditor item={item} onCancel={onCancel} onSave={onSave} onDirty={onDirty}/>; return <DocumentEditor item={item} onCancel={onCancel} onSave={onSave} onDirty={onDirty}/>; }
function Frame({ children, title, onCancel }: { children: React.ReactNode; title: string; onCancel: () => void }) { return <div className="card editor"><div className="editor-heading"><h2 className="display">{title}</h2><button type="button" onClick={onCancel} aria-label="Close editor"><X size={18}/></button></div>{children}</div> }
function HubEditor({ item, onCancel, onSave, onDirty }: { item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { const [image, setImage] = useState(item.image || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const selected = String(d.get('auctionDate')); const file = d.get('image') as File; setBusy(true); setError(''); try { const uploadedUrl = file?.size ? (await uploadFile(file)).url : image; onSave({ ...item, title: String(d.get('title')), location: String(d.get('location')), description: String(d.get('description')), auctionDate: selected, whatsapp: String(d.get('whatsapp')), image: uploadedUrl, status: d.get('status') as Status, detail: `${d.get('location')} · Auction: ${formatAuctionDate(selected)}` }); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to upload photo.'); } finally { setBusy(false); } } return <Frame title={item.title ? 'Edit hub & auction' : 'New hub'} onCancel={onCancel}><form onSubmit={submit} onChange={onDirty}><Field label="Hub name" name="title" value={item.title}/><Field label="Location" name="location" value={item.location} placeholder="Malappuram, Kerala"/><Field label="Hub description" name="description" value={item.description} textarea/><div className="field"><label htmlFor="auctionDate">Upcoming auction date</label><input id="auctionDate" name="auctionDate" type="date" defaultValue={item.auctionDate || ''} required/></div><Field label="Auction WhatsApp number" name="whatsapp" value={item.whatsapp} placeholder="919876543210" hint="Country code only—no +, spaces, or punctuation. Each hub can have a different number."/><Upload label="Hub photo" name="image" image={image} onImage={value => { setImage(value); onDirty(); }} required={!image}/>{error && <p className="form-error">{error}</p>}<StatusField value={item.status}/><Actions onCancel={onCancel} busy={busy}/></form></Frame> }
function BlogEditor({ item, onCancel, onSave, onDirty }: { item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { const [image, setImage] = useState(item.image || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const file = d.get('image') as File; setBusy(true); setError(''); try { const uploadedUrl = file?.size ? (await uploadFile(file)).url : image; onSave({ ...item, title: String(d.get('title')), subheading: String(d.get('subheading')), content: String(d.get('content')), category: String(d.get('category')), readTime: String(d.get('readTime')), image: uploadedUrl, status: d.get('status') as Status, detail: `${d.get('category')} · ${d.get('readTime')}` }); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to upload image.'); } finally { setBusy(false); } } return <Frame title={item.title ? 'Edit blog' : 'New blog'} onCancel={onCancel}><form onSubmit={submit} onChange={onDirty}><Field label="Headline" name="title" value={item.title}/><Field label="Subheading" name="subheading" value={item.subheading} textarea/><Field label="Article content" name="content" value={item.content} textarea/><Field label="Category" name="category" value={item.category} placeholder="Sustainable Farming"/><Field label="Read time" name="readTime" value={item.readTime} placeholder="6 min read"/><Upload label="Cover image" name="image" image={image} onImage={value => { setImage(value); onDirty(); }}/>{error && <p className="form-error">{error}</p>}<StatusField value={item.status}/><Actions onCancel={onCancel} busy={busy}/></form></Frame> }
function GalleryEditor({ item, onCancel, onSave, onDirty }: { item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { const [image, setImage] = useState(item.image || ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const tags=String(d.get('category')).split(',').map(tag=>tag.trim()).filter(Boolean).map(slugify); const category = tags[0] || 'general'; const file = d.get('image') as File; setBusy(true); setError(''); try { const uploadedUrl = file?.size ? (await uploadFile(file)).url : image; onSave({ ...item, title: String(d.get('title')), category, tags, slug: category, image: uploadedUrl, createdAt: item.createdAt || new Date().toISOString(), status: d.get('status') as Status, detail: tags.join(', ') || 'General' }); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to upload image.'); } finally { setBusy(false); } } return <Frame title={item.title ? 'Edit gallery image' : 'Add gallery image'} onCancel={onCancel}><form onSubmit={submit} onChange={onDirty}><Field label="Image title" name="title" value={item.title}/><Field label="Category tags" name="category" value={item.tags?.join(', ') || item.category} placeholder="Facilities, Livestock, Events" hint="Type one or more tags separated by commas. New tags create gallery categories automatically."/><Upload label="Gallery image" name="image" image={image} onImage={value => { setImage(value); onDirty(); }} required={!image}/>{error && <p className="form-error">{error}</p>}<StatusField value={item.status}/><Actions onCancel={onCancel} busy={busy}/></form></Frame> }
function TestimonialEditor({ item, onCancel, onSave, onDirty }: { item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); onSave({ ...item, title: String(d.get('title')), detail: String(d.get('detail')), quote: String(d.get('quote')), status: 'Published' }); } return <Frame title={item.title ? 'Edit testimonial' : 'Add testimonial'} onCancel={onCancel}><form onSubmit={submit} onChange={onDirty}><Field label="Person’s name" name="title" value={item.title}/><Field label="Role / details" name="detail" value={item.detail} placeholder="Veterinary Consultant"/><Field label="Testimonial" name="quote" value={item.quote} textarea/><Actions onCancel={onCancel}/></form></Frame> }
function DocumentEditor({ item, onCancel, onSave, onDirty }: { item: Item; onCancel: () => void; onSave: (item: Item) => void; onDirty: () => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const file = d.get('document') as File; if (!item.url && !file?.size) return setError('Please choose a document.'); if (file?.size > 5 * 1024 * 1024) return setError('Documents must be 5 MB or smaller.'); setBusy(true); setError(''); try { const uploaded = file?.size ? await uploadFile(file) : null; onSave({ ...item, title: String(d.get('title')), category: String(d.get('category')) || 'General', url: uploaded?.url || item.url, fileName: uploaded?.name || item.fileName, size: uploaded?.size || item.size, detail: uploaded ? `${uploaded.name} · ${(uploaded.size / 1024 / 1024).toFixed(1)} MB` : item.detail, createdAt: item.createdAt || new Date().toISOString(), status: d.get('status') as Status }); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to upload document.'); } finally { setBusy(false); } } return <Frame title={item.title ? 'Edit document' : 'Upload document'} onCancel={onCancel}><form onSubmit={submit} onChange={onDirty}><Field label="Document title" name="title" value={item.title}/><Field label="Category" name="category" value={item.category} placeholder="Policies"/><div className="field"><label htmlFor="document">Document file</label><input id="document" name="document" type="file" accept=".pdf,.doc,.docx"/><small>PDF, DOC, or DOCX · maximum file size 5 MB.</small></div>{error && <p className="form-error">{error}</p>}<StatusField value={item.status}/><Actions onCancel={onCancel} busy={busy}/></form></Frame> }
function Field({ label, name, value, placeholder, textarea, hint }: { label: string; name: string; value?: string; placeholder?: string; textarea?: boolean; hint?: string }) { return <div className="field"><label htmlFor={name}>{label}</label>{textarea ? <textarea id={name} name={name} defaultValue={value} rows={3} required/> : <input id={name} name={name} defaultValue={value} placeholder={placeholder} required/>}{hint && <small>{hint}</small>}</div> }
function Upload({ label, name, image, onImage, required }: { label: string; name: string; image: string; onImage: (value: string) => void; required?: boolean }) { function change(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (file) onImage(URL.createObjectURL(file)); } return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type="file" accept="image/*" required={required} onChange={change}/>{image && <img className="editor-preview" src={image} alt="Upload preview"/>}</div> }
function StatusField({ value }: { value: Status }) { return <div className="field"><label htmlFor="status">Status</label><select id="status" name="status" defaultValue={value}><option>Draft</option><option>Published</option><option>Active</option><option>Upcoming</option></select></div> }
function Actions({ onCancel, busy }: { onCancel: () => void; busy?: boolean }) { return <div className="editor-actions"><button type="button" className="button light" onClick={onCancel} disabled={busy}>Cancel</button><button className="button dark" disabled={busy}><Save size={16}/>{busy ? 'Saving…' : 'Save changes'}</button></div> }
function SettingsForm({ settings, onSubmit, onDirty }: { settings: Settings; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onDirty: () => void }) { return <form className="card editor settings-form" onSubmit={onSubmit} onChange={onDirty}><Field label="Site name" name="siteName" value={settings.siteName}/><Field label="Email" name="email" value={settings.email}/><Field label="Phone" name="phone" value={settings.phone}/><Field label="Address" name="address" value={settings.address} textarea/><Field label="Hero banner image URL" name="heroImage" value={settings.heroImage} placeholder="https://…" hint="Paste a hosted image URL for the homepage hero banner."/><Field label="YouTube channel or latest-video URL" name="youtubeUrl" value={settings.youtubeUrl} placeholder="https://youtube.com/@grazevalley"/><Field label="Instagram profile URL" name="instagramUrl" value={settings.instagramUrl} placeholder="https://instagram.com/grazevalley"/><button className="button dark"><Save size={16}/>Save settings</button></form> }
function slugify(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }
